#ifndef PRECOMPILED_H
#define PRECOMPILED_H

#endif // PRECOMPILED_H

#ifndef _QX_BICYCLES_PRECOMPILED_HEADER_H_
#define _QX_BICYCLES_PRECOMPILED_HEADER_H_

#include <QxOrm.h>

#include "export.h"

#endif // _QX_BICYCLES_PRECOMPILED_HEADER_H_
